### ISSUE TITLE
Close on Launch

### ISSUE THREAD

**Issue by IzzacSturnburg** [topher-au/VBFTool#1]
The application closes on start up instantly. A millisecond display of the CMD box then close.
Windows 7, with services turned off except windows. Ran administration, but nothing, not even a single file extracted. Got a read me for future texture users?

**Comment by BaconCatBug** [comment]
You need to run it via a cmd box. it will show help

**Comment by IzzacSturnburg** [comment]
Thanks I'll check that out! Appreciate the time you took to get ahold of
me. Thanks again man.
